version: '3'
services:
  db:
    build:
      context: ./docker/postgres
    environment:
      - POSTGRES_DB=dejavu
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  python:
    ports:
      - "8000:8000"
    build:
      context: ./docker/python
    volumes:
      - .:/code
    depends_on:
      - db
  frontend:
    build:
      context: ./docker/frontend
    container_name: frontend
    volumes:
      - './musicfp-frontend:/app'
      - '/app/node_modules'
    ports:
      - "3001:3000"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true